config/routes.rb
BackboneMin::Application.routes.draw do
  get "readings/index"

  resources :readings
  root "readings#index"

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  validates :sugar_level, presence:true, numericality: {greater_than_or_equal_to: 0} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  

  def index
    @readings = Reading.all  
    respond_to do |format|
      format.json {}
      format.html
    end
  end

  def create 
    flash
    @reading=Reading.new(reading_params)
    if @reading.save 
      flash[:success]= "was Created"
      redirect_to root_path
    else 
      flash[:error]=" Not Created "
      redirect_to root_path
    end 

  end


  private 

  def reading_params
    params.require(:reading).permit(:sugar_level)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackboneMin</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "MySampleApp", root_path %></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="left">
      <li class="active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "History", readings_path %></li>
    </ul>
  </section>
</nav>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%=key%> alert-dismissable">
      <button type="button" class="close" >&times;</button> <!--Pages.js For close--> 
      <%= value %>  
    </div>
  <% end %>
<%= yield %>

 <%= params %>
</body>
</html>

app/views/readings/index.html.erb
  <div class="container text-center">
    <h1>Welcome to a basic App</h1>
    <h3> To get started please enter your most recent sugar reading level in the form below</h3>
    <div class="row">
      <div id='reading-form'>
        
      </div>
    </div>
  </div>
  <div class="row recent-reading text-center">
      <div class="small-8 small-centered columns" id="readings" >
         <h3>Your 5 Most Recent Readings</h3>
          <p>Place Holder for 5 most recent Readings Collection </p>
      </div>    
  </div>

  <div id="reading_form"></div>
  <div id="reading_list"></div>





<script type="text/javascript">
  window.reading_app = new App.ReadingRouter()
</script>